steps:
  # Build the container image
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "asia-northeast1-docker.pkg.dev/nomadic-bison-459812-a8/googlehack/my-image:latest",
        ".",
      ]
  # Push the container image to Container Registry
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "asia-northeast1-docker.pkg.dev/nomadic-bison-459812-a8/googlehack/my-image",
      ]
  # Deploy container image to Cloud Run
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      [
        "run",
        "deploy",
        "my-image",
        "--image",
        "asia-northeast1-docker.pkg.dev/nomadic-bison-459812-a8/googlehack/my-image:latest",
        "--platform",
        "managed",
        "--allow-unauthenticated",
        "--ingress",
        "all",
        "--region",
        "asia-northeast1",
        "--project",
        "nomadic-bison-459812-a8",
        "--quiet",
        "--add-cloudsql-instances=nomadic-bison-459812-a8:us-central1:google-hackathon-dist",
        "--set-env-vars=SPRING_DATASOURCE_URL=jdbc:postgresql://localhost:5432/postgres,SPRING_DATASOURCE_USERNAME=postgres,SPRING_DATASOURCE_PASSWORD=morimoridist"
      ]

logsBucket: "dist_hackathon"
serviceAccount: "projects/nomadic-bison-459812-a8/serviceAccounts/ca-build-cicd@nomadic-bison-459812-a8.iam.gserviceaccount.com"
options:
  logging: GCS_ONLY